export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ALBUM_SUCCESS = 'SEARCH_ALBUM_SUCCESS';
export const SAVE_COMMENT_SUCCESS = 'SAVE_COMMENT_SUCCESS';

